#!/bin/sh
# Verifies that generated CMakeLists.txt files declare the expected
# cmake_minimum_required version.
#
# Policy:
#   - the root CMakeLists.txt (generated by `make -f cmake/setup.make root`
#     from cmake/setup_templates/CMakeLists.init) must declare
#     cmake_minimum_required(VERSION 3.20) — this is the only place the
#     call is allowed to appear.
#   - per-target CMakeLists.txt generated by the `library` and
#     `executable` targets must NOT contain cmake_minimum_required at all
#     (see bug #2 — cmake_minimum_required in an included or subdirectory
#     file can silently reset policy state).
#
# Related: bug #12 (bump cmake_minimum_required from 3.13 to 3.20+).

TEST_NAME=test_generated_cmake_minimum_required
. "$(dirname "$0")/lib/harness.sh"

EXPECTED_VERSION='3.20'

mk_sandbox

# --- root ---
mkdir foo_project
cd foo_project
ln -s "$CMAKE_SUBMODULE" cmake
make -f cmake/setup.make root >/dev/null 2>&1 || fail "make -f cmake/setup.make root exited non-zero"

assert_file_contains CMakeLists.txt "cmake_minimum_required(VERSION ${EXPECTED_VERSION}"

# --- library subdirectory ---
mkdir -p mylib/include mylib/src
(
    cd mylib
    make -f ../cmake/setup.make library >/dev/null 2>&1 || fail "make -f ../cmake/setup.make library exited non-zero"
)
assert_file_not_contains mylib/CMakeLists.txt 'cmake_minimum_required'

# --- executable subdirectory ---
mkdir -p mytool/include mytool/src
(
    cd mytool
    make -f ../cmake/setup.make executable >/dev/null 2>&1 || fail "make -f ../cmake/setup.make executable exited non-zero"
)
assert_file_not_contains mytool/CMakeLists.txt 'cmake_minimum_required'

printf '[PASS] %s\n' "$TEST_NAME"
